config/routes.rb
Rails.application.routes.draw do
  resources :sublocations
  resources :prenotations
  resources :contacts
  resources :events
  resources :categories

  
  
  get 'dashboard/index'
  get 'dashboard/note'
  get 'dashboard/passate'
  get 'dashboard/eventi'
  get 'dashboard/soldi'
  get 'dashboard/energie'
  get 'dashboard/accessi'
  get 'dashboard/attenzione'
  get 'dashboard/luoghi'
  get 'dashboard/abilita'
  get 'dashboard/attivita'
  get 'dashboard/pastcalendar'
  resources :noteslots
  resources :slots
  get 'privata/pastslot'
  get 'privata/noslot'
  get 'privata/todoslot'
  
  resources :slots 
  resources :calendars do
    resources :categories
    member do
      get 'pastslot'
      get 'noslot'
      get 'todoslot'
      
      get "passate"
      get "future"
      get "settimana"
    end
  end 
  resources :notes
  resources :profiles do
    member do
      get "profslot"
      get "pubcalendar"
      get "pastcalendar"
      get "luoghi"
      get "passate"
      get "future"
      get "settimana"
    end 
  end

  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/pastcalendar'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "pages#home"

  root "pages#calendar"
  # authenticate :user do
   # root "dashboard#index", as: :authenticated_root
  # end

  

  
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :profile
  has_many :slots
  has_many :categories
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar
  has_many :slots
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :profile, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar, optional: true
  belongs_to :category, optional: true
  has_many :slots
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :profile
  has_many :sublocations
  has_many :slots, -> { where "note_type = luoghi" }, class_name: 'Slot' 
 
  
  

  enum visibility: { privato: 0, gruppo_chiuso: 1, ticket: 2, pubblica: 3, full: 4 }
  enum note_type: { note: 0, eventi: 1, soldi: 2, energie: 3, accessi: 4, attenzione: 5, luoghi: 6, abilita: 7, attivita: 8}
  enum accesso_type: { contatto: 0, gruppo: 1 }
  enum soldi_type: { preventivo: 0, progetto: 1, acquisto: 2, vendita: 3, presto: 4, restituzione_prestito: 5, chiedo_prestito: 6, restituisco: 7  }

end

app/models/noteslot.rb
class Noteslot < ApplicationRecord
  belongs_to :profile
  belongs_to :slot
  belongs_to :note
end

app/models/prenotation.rb
class Prenotation < ApplicationRecord
  belongs_to :contact
  belongs_to :slot
  belongs_to :event
  belongs_to :user
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :notes
  has_many :calendars
  has_many :slots
  has_many :categories
  has_many :events
  
  

  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-z0-9_]+\z/,
    message: "può contenere solo lettere minuscole e numeri e _" }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar
  belongs_to :category, optional: true
  belongs_to :luogo, optional: true, class_name: 'Note', foreign_key: 'luogo_n_id'
  belongs_to :sublocation, optional: true
  belongs_to :event, optional: true

  has_many :prenotations
  has_many :noteslots


  

  enum visibility: { privato: 1, iscritti: 2, pubblico: 3}
end

app/models/sublocation.rb
class Sublocation < ApplicationRecord
  belongs_to :note
  has_many :slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile  
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_slot, only: %i[ show edit update destroy ]

  layout "dashboard"
  # GET /slots or /slots.json
  def index
    @slots = Slot.all

   
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
    # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end  
    @slots = current_user.profile.slots.where("data_start  >= ?", @data_start.beginning_of_day)
    if @notes
      @notes =  @notes.order(data_start: :desc)
    end 
    @profile = current_user.profile
  end

  # GET /slots/1 or /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots or /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to slot_url(@slot), notice: "Slot was successfully created." }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1 or /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to slot_url(@slot), notice: "Slot was successfully updated." }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1 or /slots/1.json
  def destroy
    @slot.destroy

    respond_to do |format|
      format.html { redirect_to slots_url, notice: "Slot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def slot_params
      params.require(:slot).permit(:profile_id, :calendar_id, :public, :visibility, :data_start, :data_end, :calendario_contact_note_id, :calendario_profile_id, :sublocation_id, :luogo_n_id, :event_id, :responsabile_p_id, :category_id)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/noteslots_helper.rb
module NoteslotsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/privata_helper.rb
module PrivataHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_agenda_cal_slot.html.erb
  
<%= render 'calendars/nav_cal' %> 

  <div class="mb-4 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
      <ul class="list-none flex flex-wrap -mb-px">
        
    <!--- menù dashboard-->
              <% if controller_name == "privata" && action_name == "pastslot" %>
                <li class="mr-2">
                  <%= link_to 'Passate', privata_pastslot_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Passate', privata_pastslot_path, class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
                
              <% end %>
              
              
        
              <% if  controller_name == "slots" && action_name == "index"%>
                <li class="mr-2">
                  <%= link_to 'Future', slots_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Future', slots_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>

                <% if  controller_name == "privata" && action_name == "noslot"%>
                <li class="mr-2">
                  <%= link_to 'Non calendarizzate', privata_noslot_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Non calendarizzate', privata_noslot_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>

               <% if  controller_name == "privata" && action_name == "todoslot"%>
                <li class="mr-2">
                  <%= link_to 'Da finire', privata_todoslot_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Da finire', privata_todoslot_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>
          
            <!-- end dashboard  -->         
         
          
            <!-- end pubblico  -->   
      

          
       
         
          
         
        
      </ul>
  </div>
  <div class="flex">
  


            <% if @data_start %>
              
              
                
                  
                  <%= form_with url: "/",  method: :get do |form| %>

                      <%= form.date_field :date, { required: true, class:"rounded-md p-1 m-1", value:  @data_f, onchange: 'this.form.submit();' }  %>
                      <%#= form.submit "🔍", class: "ml-2 rounded-lg py-3 px-5 bg-orange-300 inline-block font-medium"  %>
                        
                  
                    <% end %>

            <% end %>  
                  
        
            <% if user_signed_in? %>
    
              <% if current_user.profile %>
                <%= render 'notes/new_note_dropdown' %>
              <% end %>
              
            <% end %>
         

</div>



<div class="overflow-x-auto relative">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="py-3 px-6">
                    Inizio
                </th>
                <th scope="col" class="py-3 px-6">
                    Fine
                </th>
                <th scope="col" class="py-3 px-6">
                    Note
                </th>
                
            </tr>
        </thead>
        <tbody>
        <% @slots.each do |slot| %>
           
 
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= slot.data_start %>
  
                </th>
                <td class="py-4 px-6">
                     <%= slot.data_end %>
  
                </td>
                <td class="py-4 px-6">
               
                  
               <%= slot.noteslots.ids %>
                    <%#= link_to slot.note.name, slot %>
                
                </td>
               
            </tr>
          <% end %>
        </tbody>
    </table>
</div>

app/views/slots/_agenda_slot.html.erb
  
<%= render 'calendars/nav_cal' %> 

  <div class="mb-4 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
      <ul class="list-none flex flex-wrap -mb-px">
        
    <!--- menù dashboard-->
              <% if controller_name == "privata" && action_name == "pastslot" %>
                <li class="mr-2">
                  <%= link_to 'Passate', privata_pastslot_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Passate', privata_pastslot_path, class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
                
              <% end %>
              
              
        
              <% if  controller_name == "slots" && action_name == "index"%>
                <li class="mr-2">
                  <%= link_to 'Future', slots_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Future', slots_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>

                <% if  controller_name == "privata" && action_name == "noslot"%>
                <li class="mr-2">
                  <%= link_to 'Non calendarizzate', privata_noslot_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Non calendarizzate', privata_noslot_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>

               <% if  controller_name == "privata" && action_name == "todoslot"%>
                <li class="mr-2">
                  <%= link_to 'Da finire', privata_todoslot_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Da finire', privata_todoslot_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>
          
            <!-- end dashboard  -->         
         
          
            <!-- end pubblico  -->   
      

          
       
         
          
         
        
      </ul>
  </div>
  <div class="flex">
  


            <% if @data_start %>
              
              
                
                  
                  <%= form_with url: "/",  method: :get do |form| %>

                      <%= form.date_field :date, { required: true, class:"rounded-md p-1 m-1", value:  @data_f, onchange: 'this.form.submit();' }  %>
                      <%#= form.submit "🔍", class: "ml-2 rounded-lg py-3 px-5 bg-orange-300 inline-block font-medium"  %>
                        
                  
                    <% end %>

            <% end %>  
                  
        
            <% if user_signed_in? %>
    
              <% if current_user.profile %>
                <%= render 'notes/new_note_dropdown' %>
              <% end %>
              
            <% end %>
         

</div>



<div class="overflow-x-auto relative">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="py-3 px-6">
                    Inizio
                </th>
                <th scope="col" class="py-3 px-6">
                    Fine
                </th>
                <th scope="col" class="py-3 px-6">
                    Note
                </th>
                
            </tr>
        </thead>
        <tbody>
        <% @slots.each do |slot| %>
           
 
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= slot.data_start %>
  
                </th>
                <td class="py-4 px-6">
                     <%= slot.data_end %>
  
                </td>
                <td class="py-4 px-6">
                    <%= link_to slot.note.name, slot %>
  
                </td>
               
            </tr>
          <% end %>
        </tbody>
    </table>
</div>

app/views/slots/_form.html.erb
<%= form_with(model: slot) do |form| %>
  <% if slot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
        <% slot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :profile_id, style: "display: block" %>
    <%= form.text_field :profile_id, class:"input", value: current_user.profile.id%>
  </div>
 
    <div>
    <%= form.label :calendario_profile_id, style: "display: block" %>
    <%= form.text_field :calendario_profile_id, class:"input", value: current_user.profile.id%>
  </div>

  

<% if params[:calendar_id] %>  
  <div>
    <%= form.label :calendar_id, style: "display: block" %>
    <%= form.text_field :calendar_id, class:"input", value: params[:calendar_id], required: true %> 
  </div>
<% else %>
 <div>
    <%= form.label :calendar_id, style: "display: block" %>
   
      <%= form.collection_select :calendar_id, current_user.profile.calendars, :id, :name, {  prompt: "Scegli il Calendario"}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
    
  </div>
<% end %>
  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.label :visibility, style: "display: block" %>
    <%= form.select :visibility, options_for_select(Slot.visibilities.map {|k, v| [k.titleize, k]},  selected: @slot.visibility), {:prompt => 'Visibilità'}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>

  </div>


 


<% if params[:data_start] %>
  <div>
    <%= form.label :data_start, style: "display: block" %>
    <%= form.datetime_field :data_start, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true, value: (params[:data_start])[0..15]  %>
  </div>

  <div class="">
    <%= form.label :data_end, style: "display: block" %>
    <%= form.datetime_field :data_end, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true, value: (params[:data_start])[0..15]  %>
  </div>
<% else %>
  <div>
    <%= form.label :data_start, style: "display: block" %>
    <%= form.datetime_field :data_start, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true  %>
  </div>

  <div class="">
    <%= form.label :data_end, style: "display: block" %>
    <%= form.datetime_field :data_end, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true  %>
  </div>

<% end %>




<div>
    <%= form.label :luogo_n_id, style: "display: block" %>
   
      <%= form.collection_select :luogo_n_id, current_user.profile.notes.where(note_type: "luoghi"), :id, :name, {  prompt: "Scegli il Luogo"}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    
  </div>

  <% if @slot.calendar_id  %>
  <div>
    <%= form.label :category_id, style: "display: block" %>
   
      <%= form.collection_select :category_id, Calendar.find(@slot.calendar_id).categories, :id, :name, {  prompt: "Scegli la stanza o la sublocation"}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    
  </div>
<% end %>


<% if @slot.luogo_n_id  %>
  <div>
    <%= form.label :sublocation_id, style: "display: block" %>
   
      <%= form.collection_select :sublocation_id, Note.find(@slot.luogo_n_id).sublocations, :id, :name, {  prompt: "Scegli la stanza o la sublocation"}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    
  </div>
<% end %>

  


  <div>
    <%= form.label :event_id, style: "display: block" %>
   
      <%= form.collection_select :event_id, current_user.profile.events, :id, :name, {  prompt: "Scegli L'evento "}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    
  </div>

    <div>
    <%= form.label :responsabile_p_id, style: "display: block" %>
   
      <%= form.collection_select :responsabile_p_id, Profile.all, :id, :name, {  prompt: "Scegli il responsabile"}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
    
  </div>




  

  <div class="my-4">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>


 
 

app/views/slots/_slot.html.erb
<div id="<%= dom_id slot %>">
  <p>
    <h2>Profile:</h2>
    <%= slot.profile.username %>
  </p>


<h3>Profilo responsabile</h3> 
  <p>
    <strong>Contatto note_id referente calendario:</strong>
    <%= slot.calendario_contact_note_id %>
  </p>

  <p>
    <strong>Profilo referente calendario:</strong>
    <%= slot.calendario_profile_id %>
  </p>




  <p>
    <h2>Calendario:</h2>
    <%= link_to slot.calendar.name, slot.calendar %>
<br>
    <b>Categoria:</b>
      <%= link_to slot.category.name, slot.category if slot.category %>
  </p>

    <h2>Luogo:</h2>
    <%= link_to slot.luogo.name, slot.luogo if slot.luogo%>
    <br>
    <b>Sublocation:</b>
      <%= link_to slot.sublocation.name, slot.sublocation  if slot.sublocation %>
  </p>
<h2>Evento:</h2>
    <%= link_to slot.event.name, slot.event if slot.event%>
    <br>
  <p>
    <strong>Public:</strong>
    <%= slot.public %>
  </p>

  <p>
    <strong>Visibility:</strong>
    <%= slot.visibility %>
  </p>

  <p>
    <strong>Data start:</strong>
    <%= slot.data_start %>
  </p>

  <p>
    <strong>Data end:</strong>
    <%= slot.data_end %>
  </p>

</div>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render "form", slot: @slot %>

<br>

<div>
  <%= link_to "Show this slot", @slot %> |
  <%= link_to "Back to slots", slots_path %>
</div>

app/views/slots/new.html.erb
<h1>New slot</h1>

<%= render "form", slot: @slot %>

<br>
Categoria calendario
<br>
Evento

<br>
Location
<br>
Sublocation
<br>

<div>
  <%= link_to "Back to slots", slots_path %>
</div>

app/views/slots/show.html.erb
<div>
<%= render @slot %>

  

<div>
  <%= link_to "Edit this slot", edit_slot_path(@slot), class:"btn btn-primary m-2" %> 
  <%= link_to "Back to slots", slots_path, class:"btn btn-primary m-2" %>

  <%= button_to "Destroy this slot", @slot, method: :delete, class:"btn btn-danger m-2" %>
</div>
                               
                                        <a href="http://www.google.com/calendar/event?action=TEMPLATE&dates=20180821%2F20180822&text=Litmus%20Live%20London&location=etc.venues%20155%20Bishopsgate&details=Litmus%20Live%20helps%20you%20become%20a%20better%20email%20marketer%20with%20real-world%20advice%2C%20best%20practices%20%26%20practical%20takeaways." target="_blank" class="btn btn-primary m-2">
                                      Salva data
                                    </a>

<h3>Prenotazioni</h3>

<div id="prenotations">
  <% @slot.prenotations.each do |prenotation| %>
    <%= render prenotation %>
    <p>
      <%= link_to "Show this prenotation", prenotation %>
    </p>
  <% end %>
</div>

<%= link_to "New prenotation", new_prenotation_path(slot_id: @slot.id), class:"btn btn-secondary m-2" %>

</div>