config/routes.rb
Rails.application.routes.draw do
  resources :sublocations
  resources :prenotations
  resources :contacts
  resources :events
  resources :categories

  
  
  get 'dashboard/index'
  get 'dashboard/note'
  get 'dashboard/passate'
  get 'dashboard/eventi'
  get 'dashboard/soldi'
  get 'dashboard/energie'
  get 'dashboard/accessi'
  get 'dashboard/attenzione'
  get 'dashboard/luoghi'
  get 'dashboard/abilita'
  get 'dashboard/attivita'
  get 'dashboard/pastcalendar'
  resources :noteslots
  resources :slots
  get 'privata/pastslot'
  get 'privata/noslot'
  get 'privata/todoslot'
  
  resources :slots 
  resources :calendars do
    resources :categories
    member do
      get 'pastslot'
      get 'noslot'
      get 'todoslot'
      
      get "passate"
      get "future"
      get "settimana"
    end
  end 
  resources :notes
  resources :profiles do
    member do
      get "profslot"
      get "pubcalendar"
      get "pastcalendar"
      get "luoghi"
      get "passate"
      get "future"
      get "settimana"
    end 
  end

  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/pastcalendar'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "pages#home"

  root "pages#calendar"
  # authenticate :user do
   # root "dashboard#index", as: :authenticated_root
  # end

  

  
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :profile
  has_many :slots
  has_many :categories
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar
  has_many :slots
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :profile, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar, optional: true
  belongs_to :category, optional: true
  has_many :slots
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :profile
  has_many :sublocations
  has_many :slots, -> { where "note_type = luoghi" }, class_name: 'Slot' 
 
  
  

  enum visibility: { privato: 0, gruppo_chiuso: 1, ticket: 2, pubblica: 3, full: 4 }
  enum note_type: { note: 0, eventi: 1, soldi: 2, energie: 3, accessi: 4, attenzione: 5, luoghi: 6, abilita: 7, attivita: 8}
  enum accesso_type: { contatto: 0, gruppo: 1 }
  enum soldi_type: { preventivo: 0, progetto: 1, acquisto: 2, vendita: 3, presto: 4, restituzione_prestito: 5, chiedo_prestito: 6, restituisco: 7  }

end

app/models/noteslot.rb
class Noteslot < ApplicationRecord
  belongs_to :profile
  belongs_to :slot
  belongs_to :note
end

app/models/prenotation.rb
class Prenotation < ApplicationRecord
  belongs_to :contact
  belongs_to :slot
  belongs_to :event
  belongs_to :user
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :notes
  has_many :calendars
  has_many :slots
  has_many :categories
  has_many :events
  
  

  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-z0-9_]+\z/,
    message: "può contenere solo lettere minuscole e numeri e _" }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar
  belongs_to :category, optional: true
  belongs_to :luogo, optional: true, class_name: 'Note', foreign_key: 'luogo_n_id'
  belongs_to :sublocation, optional: true
  belongs_to :event, optional: true

  has_many :prenotations
  has_many :noteslots


  

  enum visibility: { privato: 1, iscritti: 2, pubblico: 3}
end

app/models/sublocation.rb
class Sublocation < ApplicationRecord
  belongs_to :note
  has_many :slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user! 
  def index
  end

  def passate
    
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
    # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end  
    @notes = current_user.profile.notes.where("data_start < ?", @data_start.beginning_of_day )
    if @notes
      @notes =  @notes.order(data_start: :desc)
    end 
    @profile = current_user.profile

  end

  def pastcalendar
    @slots = Slot.all

   
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
    # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end  
    @slots = current_user.profile.slots.where("data_start  <= ?", @data_start.beginning_of_day)
    if @notes
      @notes =  @notes.order(data_start: :desc)
    end 
    @profile = current_user.profile
  end

  def note
  end

  def eventi
  end

  def soldi
  end

  def energie
  end

  def accessi
  end

  def attenzione
  end

  def luoghi
  end

  def abilita
  end

  def attivita
  end


end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/noteslots_helper.rb
module NoteslotsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/privata_helper.rb
module PrivataHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/dashboard/_nav_dash.html.erb
<nav class="absolute top-0 left-0 w-full z-10 bg-transparent md:flex-row md:flex-nowrap md:justify-start flex items-center p-4">
  <div class="w-full mx-autp items-center flex justify-between md:flex-nowrap flex-wrap md:px-10 px-4">
    <%= link_to 'Dashboard', dashboard_index_path,  class:"text-white text-sm uppercase hidden lg:inline-block font-semibold" %>
    <form class="md:flex hidden flex-row flex-wrap items-center lg:ml-auto mr-3">
      <div class="relative flex w-full flex-wrap items-stretch">
        <input
                type="text"
                placeholder="Search here..."
                class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 relative bg-white bg-white rounded text-sm shadow outline-none focus:outline-none focus:ring w-full pl-10"
              />
      </div>
    </form> 
    <!--drop down start-->
    <div class="inline-block  leading-none rounded no-underline text-gray hover:text-gray-900 hover:bg-white -mr-8 lg:mt-0 font-medium tracking-wide ">
        <div class="relative" data-controller="dropdown">
          <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="inline-block select-none">
            <span
                class="w-12 h-12 text-sm text-white bg-blueGray-200 inline-flex items-center justify-center rounded-full"
                ><img
                  alt="..."
                  class="w-full rounded-full align-middle border-none shadow-lg"
                  src="<%= image_url('template/team-1-800x800.jpg') %>"
              />
            </span>
          </div>
          <div data-dropdown-target="menu" class="absolute right-0 mt-2 hidden">
            <div class="bg-white shadow rounded border overflow-hidden">
              <%= link_to edit_registration_path(current_user), class:"text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-blueGray-700"  do %>
            
                Impostazioni
              <% end %>
              <div class="h-0 my-2 border border-solid border-blueGray-100">
              </div>
              

              <%= button_to(
                  "Esci",
                  destroy_user_session_path,
                  method: :delete,
                  
                  class:"text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-blueGray-700"
                ) %> 
              
          
            </div>
          </div>
        </div>  

      </div>
      <!--drop down end --->
      <ul
        class="flex-col md:flex-row list-none items-center hidden md:flex"
      >
      
      
          
          
        
      </ul>

</nav>

app/views/dashboard/_pas_fut_note.html.erb
<div class="mb-4 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="list-none flex flex-wrap -mb-px">
      
        <% if  (controller_name == "dashboard" && action_name == "passate") || (controller_name == "notes" && action_name == "index")  %>
          <!--- menù dashboard-->
           
            
      
            <% if  (controller_name == "dashboard" && action_name == "passate") || (controller_name == "profiles" && action_name == "future")%>
              <li class="mr-2">
                <%= link_to 'Passate', dashboard_passate_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% else  %>
              <li class="mr-2">
                <%= link_to 'Passate', dashboard_passate_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
            
            <% end %>

             <% if controller_name == "notes" && action_name == "index" %>
              <li class="mr-2">
                <%= link_to 'Future', notes_path,class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% else %>
              <li class="mr-2">
                <%= link_to 'Future', notes_path, class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
              
            <% end %>
            










        
          <!-- end dashboard  -->         
        <% elsif (controller_name == "profiles" && action_name == "passate") || (controller_name == "profiles" && action_name == "future")  %>
      
            <!--- menù pubblico -->
            <% if controller_name == "profiles" && action_name == "passate" %>
              <li class="mr-2">
                <%= link_to 'Passate', passate_profile_path(@profile), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% else %>
              <li class="mr-2">
                <%= link_to 'Passate', passate_profile_path(@profile), class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
              
            <% end %>
            
            
      
              <% if  (controller_name == "pages" && action_name == "home") || (controller_name == "profiles" && action_name == "future")%>
              <li class="mr-2">
                <%= link_to 'Future', future_profile_path(@profile), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% elsif  (controller_name == "notes" && action_name == "index") || (controller_name == "profiles" && action_name == "passate") %>
              <li class="mr-2">
                <%= link_to 'Future', future_profile_path(@profile),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
            
            <% end %>


          <% if  (controller_name == "profiles" && action_name == "settimana") %>
              <li class="mr-2">
                <%= link_to 'Settimana',  settimana_profile_path(@profile), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% else   %>
              <li class="mr-2">
                <%= link_to 'Settimana',  settimana_profile_path(@profile),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
            
            <% end %>

        
          <!-- end pubblico  -->   
      
        <% end %>

        
    
      
        
      
      
    </ul>
</div>

app/views/dashboard/accessi.html.erb
<h1>Dashboard#accessi</h1>
<p>Find me in app/views/dashboard/accessi.html.erb</p>

app/views/dashboard/attenzione.html.erb
<h1>Dashboard#attenzione</h1>
<p>Find me in app/views/dashboard/attenzione.html.erb</p>

app/views/dashboard/attivita.html.erb
<h1>Dashboard#attivita</h1>
<p>Find me in app/views/dashboard/attivita.html.erb</p>

app/views/dashboard/eventi.html.erb
<h1>Dashboard#eventi</h1>
<p>Find me in app/views/dashboard/eventi.html.erb</p>

app/views/dashboard/luoghi.html.erb
<h1>Dashboard#luoghi</h1>
<p>Find me in app/views/dashboard/luoghi.html.erb</p>

app/views/dashboard/note.html.erb
<h1>Dashboard#note</h1>
<p>Find me in app/views/dashboard/note.html.erb</p>

app/views/dashboard/passate.html.erb
        
    <div class="w-full mb-12 md:px-4">
              <div
                class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-white"
              >
                <div class="rounded-t mb-0 px-4 py-3 border-0">
                  <div class="flex flex-wrap items-center">
                     <!--Nav  tempo --->
                    
                      <%= render 'dashboard/pas_fut_note' %>
                    
                      <div class="flex">
                        <% if @data_start %>    
                          <%= form_with url: "/dashboard/passate",  method: :get do |form| %>

                                  <%= form.date_field :date, { required: true, class:"rounded-md p-1 m-1", value:  @data_f, onchange: 'this.form.submit();' }  %>
                                  <%#= form.submit "🔍", class: "ml-2 rounded-lg py-3 px-5 bg-orange-300 inline-block font-medium"  %>
                          <% end %>
                        <% end %>  
                        <% if user_signed_in? %>
                          <% if current_user.profile %>
                            <%= render 'notes/new_note_dropdown' %>
                          <% end %> 
                        <% end %>
                      </div>
                   
                     <!-- nav tempo --->
                   
                 
                  </div>
                   <div
                      class="relative w-full px-4 max-w-full flex-grow flex-1"
                    >
                    
                      <h3 class="font-semibold text-lg text-blueGray-700">
                        Note
                      </h3>
                      
                    </div>
                </div>
                <div class="block w-full overflow-x-auto">
                  <!-- Projects table -->
                  <%= render 'notes/table_notes' %>
                </div>
              </div>
            </div>
          
          </div>
          <%= render 'dashboard/footer_dash' %>
        </div>
      </div>
    </div>
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
    <script type="text/javascript">
      /* Make dynamic date appear */
      (function () {
        if (document.getElementById("get-current-year")) {
          document.getElementById("get-current-year").innerHTML =
            new Date().getFullYear();
        }
      })();
      /* Sidebar - Side navigation menu on mobile/responsive mode */
      function toggleNavbar(collapseID) {
        document.getElementById(collapseID).classList.toggle("hidden");
        document.getElementById(collapseID).classList.toggle("bg-white");
        document.getElementById(collapseID).classList.toggle("m-2");
        document.getElementById(collapseID).classList.toggle("py-3");
        document.getElementById(collapseID).classList.toggle("px-6");
      }
      /* Function for dropdowns */
      function openDropdown(event, dropdownID) {
        let element = event.target;
        while (element.nodeName !== "A") {
          element = element.parentNode;
        }
        Popper.createPopper(element, document.getElementById(dropdownID), {
          placement: "bottom-start"
        });
        document.getElementById(dropdownID).classList.toggle("hidden");
        document.getElementById(dropdownID).classList.toggle("block");
      }
    </script>
  </div>



<!--p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_note_path %-->

app/views/dashboard/pastcalendar.html.erb
<!--https://tailwinduikit.com/components/marketing/page_section/team--->

               
<div class="mx-auto  text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="list-none flex flex-wrap -mb-px">
            
            <!--- menù pubblico -->
						  <% if  controller_name == "dashboard" && action_name == "pastcalendar" %>
              <li class="mr-2">
                <%= link_to 'Passate', dashboard_pastcalendar_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% else %>
              <li class="mr-2">
                <%= link_to 'Passate', dashboard_pastcalendar_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
            
            <% end %>

            <li><% if @data_start %>
              
              
                
                  
                  <%= form_with url: "/slots", class: "mx-auto", method: :get do |form|%>

                      <%= form.date_field :date, { required: true, class:"rounded-md p-1 m-1", value:  @data_f, onchange: 'this.form.submit();' }  %>
                      <%#= form.submit "🔍", class: "ml-2 rounded-lg py-3 px-5 bg-orange-300 inline-block font-medium"  %>
                        
                  
                    <% end %>

            <% end %>  </li>

            <% if controller_name == "slots" && action_name == "index" %>
              <li class="mr-2">
                <%= link_to 'Future', slots_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                
                
              </li>
            <% else %>
              <li class="mr-2">
                <%= link_to 'Future', slots_path, class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
              </li>
              
            <% end %>
            
            
      
            

        
    

        
    
      
        
      
      
    </ul>
</div>
                <div class="w-full bg-gray-100 dark:bg-gray-800 px-10 pt-10 mx-auto lg:flex">

                    <!-- Profile responsabile start--->

                    
                        <div role="list" aria-label="Behind the scenes People " class="m-2 lg:flex lg:col-1">
                           
                            <div role="listitem" class=" relative mt-16 mb-32 sm:mb-24">
                             
                            </div>
                           
                        </div>
                       
                  
                    <!-- Profile responsabile end-->        

                    <!--- Event list start --->
                    <!-- component -->
<style>
  #journal-scroll::-webkit-scrollbar {
            width: 4px;
            cursor: pointer;
            /*background-color: rgba(229, 231, 235, var(--bg-opacity));*/

        }
        #journal-scroll::-webkit-scrollbar-track {
            background-color: rgba(229, 231, 235, var(--bg-opacity));
            cursor: pointer;
            /*background: red;*/
        }
        #journal-scroll::-webkit-scrollbar-thumb {
            cursor: pointer;
            background-color: #a0aec0;
            /*outline: 1px solid slategrey;*/
        }
</style>





                    
                    <div class="w-full h-full overflow-auto shadow bg-white lg:col-3" id="journal-scroll">

                    <!--div class="bg-white text-sm text-gray-500 font-bold px-5 py-2 shadow border-b border-gray-300">
                        Tracking events
                    </div-->
                    <table class="w-full">
                     <thead class="bg-white text-sm text-gray-500 font-bold px-5 py-2 shadow border-b border-gray-300">
                              <tr class="relative transform scale-100
                                       bg-opacity-25">
                                <td class="pl-5 pr-3 whitespace-no-wrap">
                                     	<%= link_to "+", new_slot_path(data_start: @data_start), class:"bg-pink-500 text-white active:bg-pink-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" %>
                                </td>
                                
                                <td>
                                  Referente Calendario  
                                </td>

                                <td class="px-2 py-2 whitespace-no-wrap">
                                  Evento
                                </td>
                               
                                <td>
                                  Pubblico
                                </td>
                                <td>
                                  Visibility
                                </td>
                                 <td>
                                  Luogo
                                </td>
                                <td>
                                  Subluogo
                                </td>
                                 <td>
                                  Calendario
                                </td>
                                 <td>
                                  Categoria
                                </td>
                                

                            </tr>
                            </thead>


                        <tbody class="">
                        
                          <% @slots.each do |slot| %>
                          <% if slot.data_start.strftime("%A - %d %b %Y") != @data_s_slot %>
                            
                      
                            <tr> 
                            <td colspan="4" class="pl-4"> 
                              <h4 class=""><%= slot.data_start.strftime("%A - %d %b %Y") if slot.data_start %>
                               </h4>
                            </td>
                               </tr>
                            <%  @data_s_slot = slot.data_start.strftime("%A - %d %b %Y") %>
                          <% end %>
                        
                              <tr class="relative transform scale-100
                                        text-xs py-1 border-b-2 
                                        <% if slot.data_start && slot.data_end %>
                                        <% if slot.data_start < DateTime.now && slot.data_end < DateTime.now  %>
                                        <% end %>
                                         border-blue-100 cursor-default

                                bg-blue-500 bg-opacity-25 <% end %>">
                                <td class="pl-5 pr-3 whitespace-no-wrap">
                                  
                                <% if slot.data_start.nil? && slot.data_end.nil?  %>
                                  <%= link_to edit_slot_path(slot) do %>
                                       scegli ora
                                       <% end %>
                                 <% else %>
                                  <%= link_to slot do %>
                                  
                                  
                                  
                                   
                                    <%= slot.data_start.strftime("%H:%M") if slot.data_start %>
                                    <div><%= slot.data_end.strftime("%H:%M") if slot.data_end %></div>

                                  <% end %>


                               
                                  <% end %>
                                </td>
                                <td>
                                    <% if slot.calendario_profile_id %>
                                       <% prof = Profile.find(slot.calendario_profile_id) %>
                                       <%= link_to  profslot_profile_path(prof) do %> 
                                        <div class="flex">
                                        <div>
                                       
                                        <img src="<%= h_avatar_url(slot.calendario_profile_id) %>" alt="Display Picture of Andres Berlin" role="img" class="rounded-full w-8 h-8 shadow-md" />
                                       </div>
                                        <div>
                                        <%=  prof.name %>
                                        <br>
                                          <%=  prof.username %>
                                           </div>
                                        </div>
                                        <% end %>
                                    <% elsif slot.calendario_contact_note_id %>
                                       <% prof = Profile.find(slot.calendario_profile_id) %>
                                           <%= link_to profslot_profile_path(prof) do %> 
                                        <div class="flex">
                                        <div>
                                        <img src="<%= prof.avatar_url %>" alt="Display Picture of Andres Berlin" role="img" class="rounded-full w-8 h-8 shadow-md" />
                                        </div>
                                        <div>
                                        <%= prof.name %>
                                        <br>
                                          <%= prof.username %>
                                          </div>
                                          </div>
                                        <% end %>
                                    <% end %>
                                </td>

                                <td class="px-2 py-2 whitespace-no-wrap">

                                    <%= noteslot = slot.noteslots.where(note_type: "evento").first  %>
                                   <% if slot.event %>
                                     

                                     <%=  slot.event.name %>
                                  <% else %>
                                    Aggiungi Evento
                                  <% end %>
                                </td>
                                
                                <td>
                                   <%=  slot.public %>
                                </td>
                                <td>
                                 <%=  slot.visibility %>
                                </td>
                                <td>
                                 <%=  link_to slot.luogo.name if slot.luogo %>
                                </td>
                                  <td>
                                   <%=  link_to slot.sublocation.name if slot.sublocation %>
                                </td>
                                <td>
                                  <%= link_to slot.calendar.name, slot.calendar if slot.calendar %>
                                </td>
                                <td>
                                   <%= link_to slot.category.name, slot.calendar if  slot.category %>
                                </td>

                            </tr>
                            <% end %>
                       </tbody>
                    </table>
                    </div>
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    

 </div>
                    <!-- Event list end -->

            

             </div> </div>

app/views/dashboard/soldi.html.erb
<h1>Dashboard#soldi</h1>
<p>Find me in app/views/dashboard/soldi.html.erb</p>