config/routes.rb
Rails.application.routes.draw do
  resources :sublocations
  resources :prenotations
  resources :contacts
  resources :events
  resources :categories

  
  
  get 'dashboard/index'
  get 'dashboard/note'
  get 'dashboard/passate'
  get 'dashboard/eventi'
  get 'dashboard/soldi'
  get 'dashboard/energie'
  get 'dashboard/accessi'
  get 'dashboard/attenzione'
  get 'dashboard/luoghi'
  get 'dashboard/abilita'
  get 'dashboard/attivita'
  get 'dashboard/pastcalendar'
  resources :noteslots
  resources :slots
  get 'privata/pastslot'
  get 'privata/noslot'
  get 'privata/todoslot'
  
  resources :slots 
  resources :calendars do
    resources :categories
    member do
      get 'pastslot'
      get 'noslot'
      get 'todoslot'
      
      get "passate"
      get "future"
      get "settimana"
    end
  end 
  resources :notes
  resources :profiles do
    member do
      get "profslot"
      get "pubcalendar"
      get "pastcalendar"
      get "luoghi"
      get "passate"
      get "future"
      get "settimana"
    end 
  end

  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/pastcalendar'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "pages#home"

  root "pages#calendar"
  # authenticate :user do
   # root "dashboard#index", as: :authenticated_root
  # end

  

  
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :profile
  has_many :slots
  has_many :categories
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar
  has_many :slots
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :profile, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar, optional: true
  belongs_to :category, optional: true
  has_many :slots
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :profile
  has_many :sublocations
  has_many :slots, -> { where "note_type = luoghi" }, class_name: 'Slot' 
 
  
  

  enum visibility: { privato: 0, gruppo_chiuso: 1, ticket: 2, pubblica: 3, full: 4 }
  enum note_type: { note: 0, eventi: 1, soldi: 2, energie: 3, accessi: 4, attenzione: 5, luoghi: 6, abilita: 7, attivita: 8}
  enum accesso_type: { contatto: 0, gruppo: 1 }
  enum soldi_type: { preventivo: 0, progetto: 1, acquisto: 2, vendita: 3, presto: 4, restituzione_prestito: 5, chiedo_prestito: 6, restituisco: 7  }

end

app/models/noteslot.rb
class Noteslot < ApplicationRecord
  belongs_to :profile
  belongs_to :slot
  belongs_to :note
end

app/models/prenotation.rb
class Prenotation < ApplicationRecord
  belongs_to :contact
  belongs_to :slot
  belongs_to :event
  belongs_to :user
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :notes
  has_many :calendars
  has_many :slots
  has_many :categories
  has_many :events
  
  

  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-z0-9_]+\z/,
    message: "può contenere solo lettere minuscole e numeri e _" }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :profile
  belongs_to :calendar
  belongs_to :category, optional: true
  belongs_to :luogo, optional: true, class_name: 'Note', foreign_key: 'luogo_n_id'
  belongs_to :sublocation, optional: true
  belongs_to :event, optional: true

  has_many :prenotations
  has_many :noteslots


  

  enum visibility: { privato: 1, iscritti: 2, pubblico: 3}
end

app/models/sublocation.rb
class Sublocation < ApplicationRecord
  belongs_to :note
  has_many :slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
     # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
     # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end 
    @notes = current_user.profile.notes.where("data_start > ?", @data_start.beginning_of_day) 
    if @notes
      @notes =  @notes.order(data_start: :asc)
    end 
    @profile = current_user.profile
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.profile.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.profile.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:profile_id, :name, :description, :body, :note_type, :euro_pagati, :euro_ricevuti, :data_start, :data_end, :lat, :long, :google_maps_url, :stato_attention, :visibility, :pubblica)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/noteslots_helper.rb
module NoteslotsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/privata_helper.rb
module PrivataHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/notes/_agenda_note.html.erb
  <% if controller_name != "profiles" %>
    <%= render 'calendars/nav_cal' %>
  <% end %>


  <div class="mb-4 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
      <ul class="list-none flex flex-wrap -mb-px">
         
          <% if  (controller_name == "pages" && action_name == "home") || (controller_name == "notes" && action_name == "index")  %>
            <!--- menù dashboard-->
              <% if controller_name == "notes" && action_name == "index" %>
                <li class="mr-2">
                  <%= link_to 'Passate', notes_path,class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Passate', notes_path, class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
                
              <% end %>
              
              
        
              <% if  (controller_name == "pages" && action_name == "home") || (controller_name == "profiles" && action_name == "future")%>
                <li class="mr-2">
                  <%= link_to 'Future', pages_home_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% elsif  (controller_name == "notes" && action_name == "index") || (controller_name == "profiles" && action_name == "passate") %>
                <li class="mr-2">
                  <%= link_to 'Future', pages_home_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>












     







          
            <!-- end dashboard  -->         
          <% elsif (controller_name == "profiles" && action_name == "passate") || (controller_name == "profiles" && action_name == "future")  %>
        
              <!--- menù pubblico -->
              <% if controller_name == "profiles" && action_name == "passate" %>
                <li class="mr-2">
                  <%= link_to 'Passate', passate_profile_path(@profile), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Passate', passate_profile_path(@profile), class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
                
              <% end %>
              
              
        
                <% if  (controller_name == "pages" && action_name == "home") || (controller_name == "profiles" && action_name == "future")%>
                <li class="mr-2">
                  <%= link_to 'Future', future_profile_path(@profile), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% elsif  (controller_name == "notes" && action_name == "index") || (controller_name == "profiles" && action_name == "passate") %>
                <li class="mr-2">
                  <%= link_to 'Future', future_profile_path(@profile),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>


            <% if  (controller_name == "profiles" && action_name == "settimana") %>
                <li class="mr-2">
                  <%= link_to 'Settimana',  settimana_profile_path(@profile), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else   %>
                <li class="mr-2">
                  <%= link_to 'Settimana',  settimana_profile_path(@profile),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>

          
            <!-- end pubblico  -->   
        
          <% end %>

          
       
         
          
         
        
      </ul>
  </div>
  <div class="flex">
  


            <% if @data_start %>
              
              
                
                  
                  <%= form_with url: "/",  method: :get do |form| %>

                      <%= form.date_field :date, { required: true, class:"rounded-md p-1 m-1", value:  @data_f, onchange: 'this.form.submit();' }  %>
                      <%#= form.submit "🔍", class: "ml-2 rounded-lg py-3 px-5 bg-orange-300 inline-block font-medium"  %>
                        
                  
                    <% end %>

            <% end %>  
                  
        
            <% if user_signed_in? %>
    
              <% if current_user.profile %>
                <%= render 'notes/new_note_dropdown' %>
              <% end %>
              
            <% end %>
         

</div>

<ul class="list-none relative border-l border-gray-200 dark:border-gray-700">                  
   
   
      <% @notes.each do |note| %>
        <li class="ml-6">        
          <span class="flex absolute -left-12 justify-center items-center w-16 h-16  rounded-full ring-8 ring-white ">
             

               <%= render_svg "notes/#{note.note_type}", styles: "w-5 h-5 fill-current group-hover:text-indigo-600 text-gray-600 mr-3" %>
        
             
              
          </span>
          <% if user_signed_in? %> 
            <% if current_user.profile %>
            <% if current_user.profile.id == note.profile.id %>
            <%= current_user.profile.id  %>

              <span class="text-black -mt-2">note_id: <%= note.id %></span>  
            <% end %> 
            <% end %>    
          <% end %> 
          <h3 class="flex items-center mb-1 text-lg font-semibold text-gray-900 dark:text-white"> 
          <%= link_to note.name, note %>
           <!--span class="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ml-3">Latest</span-->
          </h3>
          <time class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
             <% if note.data_start.strftime("%Y-%m-%d") != @data_f %>
   
             
               <%= note.data_start.strftime("%d-%m-%Y") %> |
             <% end %>   
            
            <%= note.data_start.strftime("%H:%M") %> -
            
            <% if note.data_end %>
              <% if  note.data_start.strftime("%d-%m-%Y") ==  note.data_end.strftime("%d-%m-%Y") %>
                 <%= note.data_end.strftime("%H:%M") %>
              
              <% else %>
                <%= note.data_end.strftime("%d-%m-%Y %H:%M") %>
              <% end %>
            <% end %>
          
             
             </time>
          <!--p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400"> <%= note.description %></p-->
          
          <!--a href="#" class="inline-flex items-center py-2 px-4 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:outline-none focus:ring-gray-200 focus:text-blue-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700">
            <svg class="mr-2 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a2 2 0 00-2 2v12a2 2 0 002 2h8a2 2 0 002-2V7.414A2 2 0 0015.414 6L12 2.586A2 2 0 0010.586 2H6zm5 6a1 1 0 10-2 0v3.586l-1.293-1.293a1 1 0 10-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 11.586V8z" clip-rule="evenodd"></path></svg> 
          Download ZIP
          </a-->
      </li>
      <% end %>
  

  
    <!--li class="mb-10 ml-6">
        <span class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-blue-200 rounded-full ring-8 ring-white ">
            <svg aria-hidden="true" class="w-3 h-3 text-blue-600 dark:text-blue-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
        </span>
        <h3 class="mb-1 text-lg font-semibold text-gray-900 dark:text-white">Flowbite Figma v1.3.0</h3>
        <time class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Released on December 7th, 2021</time>
        <p class="text-base font-normal text-gray-500 dark:text-gray-400">All of the pages and components are first designed in Figma and we keep a parity between the two versions even as we update the project.</p>
    </li>
    <li class="ml-6">
        <span class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-blue-200 rounded-full ring-8 ring-white ">
            <svg aria-hidden="true" class="w-3 h-3 text-blue-600 dark:text-blue-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
        </span>
        <h3 class="mb-1 text-lg font-semibold text-gray-900 dark:text-white">Flowbite Library v1.2.2</h3>
        <time class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Released on December 2nd, 2021</time>
        <p class="text-base font-normal text-gray-500 dark:text-gray-400">Get started with dozens of web components and interactive elements built on top of Tailwind CSS.</p>
    </li-->
</ul>

app/views/notes/_form.html.erb
<div class="lg:w-96">
<%= form_with(model: note, class:"lg:w-96") do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :profile_id, style: "display: block" %>
    <%= form.text_field :profile_id, class:"input" %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true, class:"input" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class:"input" %>
  </div>

  <div>
   <a href="https://pandao.github.io/editor.md/en.html" target="_blank">Vai all'editor</a>
  
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class:"input" %>
  </div>


 <div>
    <%= form.label :note_type, style: "display: block" %>
     <% if params[:note_type] %>
     
          <%= form.hidden_field :note_type, value: params[:note_type], required: true %>   
     <div class="flex">
        <b>  <%= render_svg "notes/#{params[:note_type]}", styles: "w-5 h-5 fill-current group-hover:text-indigo-600 text-gray-600 mr-3" %>
               <%= params[:note_type] %></b> 
               </div>
        <% else %>
        
          <%= form.select :note_type, options_for_select(Note.note_types.map {|k, v| [k.titleize, k]},  selected: @note.note_type), {:prompt => 'Tipo di nota'}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
        <% end %>

  
  </div>

 

  <div>
    <%= form.label :euro_pagati, style: "display: block" %>
    <%= form.text_field :euro_pagati, class:"input" %>
  </div>

  <div>
    <%= form.label :euro_ricevuti, style: "display: block" %>
    <%= form.text_field :euro_ricevuti, class:"input" %>
  </div>

  <div>
    <%= form.label :data_start, style: "display: block" %>
    <% if params[:data_start]  %>
         <%= form.datetime_field :data_start, value: params[:data_start] + "T12:00", class:"input" %>
    <% else %>
     <%= form.datetime_field :data_start, class:"input"  %>
    <% end %>
 
  </div>

  <div>
    <%= form.label :data_end, style: "display: block" %>

    <% if params[:data_start]  %>
         <%= form.datetime_field :data_end, value: params[:data_start] + "T12:00", class:"input" %>
    <% else %>
     <%= form.datetime_field :data_end, class:"input"  %>
    <% end %>
   
  </div>

  <div>
    <%= form.label :lat, style: "display: block" %>
    <%= form.text_field :lat, class:"input" %>
  </div>

  <div>
    <%= form.label :long, style: "display: block" %>
    <%= form.text_field :long, class:"input" %>
  </div>

  <div>
    <%= form.label :google_maps_url, style: "display: block" %>
    <%= form.text_area :google_maps_url, class:"input" %>
  </div>

  <div>
    <%= form.label :stato_attention, style: "display: block" %>
    <%= form.number_field :stato_attention, class:"input" %>
  </div>

  <div>
    <%= form.label :visibility, style: "display: block" %>
    <%= form.number_field :visibility , class:"input"%>
  </div>

  <div class="m-8">
    <%= form.label :pubblica, style: "display: block" %>
    <%= form.check_box :pubblica %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/notes/_new_note_dropdown.html copy.erb
<!-- crea nota----> 
  <% if user_signed_in? %>
  <div data-controller="dropdown"  class="btn   <% if controller_name == "notes" && action_name == "edit" %>hidden<% end %>">

    <%= link_to "#", class: "no-underline flex justify-between text-sm tracking-wide items-center font-semibold select-none py-2", data: { action: "click->dropdown#toggle click@window->dropdown#hide" } do %>
          
    <% if action_name == "new" && controller_name == "notes" %>
      <% if params[:note_type].nil? %>
        <%= render_svg "icons/create", styles: "group-hover:text-indigo-600 fill-current text-gray-600", title: "Create submission" %>
      <% else %> 
        <%= render_svg "notes/#{params[:note_type].first}", styles: "w-5 h-5 fill-current group-hover:text-indigo-600 text-gray-600 mr-3" %>
        <%= params[:note_type].first %>
      <% end %> 
    <% else %>
      <%= render_svg "icons/create", styles: "group-hover:text-indigo-600 fill-current text-gray-600", title: "Create submission" %>
    <% end %>    


      <%= render_svg "icons/chevron-down", styles: "ml-2 w-4 h-4 text-gray-600" %>
    <% end %>
    <div class="relative">
      <ul style="z-index:50;" class="list-none hidden absolute top-2 -right-8 bg-white min-w-[200px] border border-gray-400 rounded shadow-lg" data-dropdown-target="menu">
          
        
        
          <% Note.note_types.each do |note| %> 
            <li>
            
            <% if @activity.present? %>
              <% act_id = @activity.id %>
            <% else %>
             <% act_id = nil%>
            <% end %>
           
              <%= link_to new_note_path(note_type: note.first, data_start: @data_f), class: "hover:bg-indigo-50 hover:text-indigo-600 text-gray-600 no-underline block py-3 px-4 flex items-center group rounded-t" do %>
                <%#= render_svg "notes/#{note.first}", styles: "w-5 h-5 fill-current group-hover:text-indigo-600 text-gray-600 mr-3" %>
                  <%= note.first %>
              <% end %>
            </li>
          <% end %>
          
      
      </ul>

    </div>
  </div>   
<!-- fine crea nota -->
  <% end %>

app/views/notes/_new_note_dropdown.html.erb
<!-- crea nota----> 
  <% if user_signed_in? %>
  <div data-controller="dropdown"  class="btn   <% if controller_name == "notes" && action_name == "edit" %>hidden<% end %>">

    <%= link_to "#", class: "no-underline flex justify-between text-sm tracking-wide items-center font-semibold select-none py-2", data: { action: "click->dropdown#toggle click@window->dropdown#hide" } do %>
        
    <% if action_name == "new" && controller_name == "notes" %>
      <% if params[:note_type].nil? %>
        <%= render_svg "icons/create", styles: "group-hover:text-indigo-600 fill-current text-gray-600", title: "Create submission" %>
      <% else %> 
        <%= render_svg "notes/#{params[:note_type].first}", styles: "w-5 h-5 fill-current group-hover:text-indigo-600 text-gray-600 mr-3" %>
        <%= params[:note_type].first %>
      <% end %> 
    <% else %>
      <%= render_svg "icons/create", styles: "group-hover:text-indigo-600 fill-current text-gray-600", title: "Create submission" %>
    <% end %>    


      <%= render_svg "icons/chevron-down", styles: "ml-2 w-4 h-4 text-gray-600" %>
    <% end %>
    <div class="relative">
      <ul style="z-index:50;" class="list-none hidden absolute top-2 -right-8 bg-white min-w-[200px] border border-gray-400 rounded shadow-lg" data-dropdown-target="menu">
          
        
        
          <% Note.note_types.each do |note| %> 
            <li>
            
            <% if @activity.present? %>
              <% act_id = @activity.id %>
            <% else %>
             <% act_id = nil%>
            <% end %>
           
              <%= link_to new_note_path(note_type: note.first, data_start: @data_f), class: "hover:bg-indigo-50 hover:text-indigo-600 text-gray-600 no-underline block py-3 px-4 flex items-center group rounded-t" do %>
                <%= render_svg "notes/#{note.first}", styles: "w-5 h-5 fill-current group-hover:text-indigo-600 text-gray-600 mr-3" %>
                  <%= note.first %>
              <% end %>
            </li>
          <% end %>
          
      
      </ul>

    </div>
  </div>   
<!-- fine crea nota -->
  <% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", root_path %>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", root_path %>
</div>

app/views/notes/show.html.erb
<div class="mx-auto my-8">
<%= link_to "Aggiungi a un calendario", new_slot_path(note_id: @note.id), class:"btn btn-primary m-4" %>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note), class:"btn btn-primary outline m-2" %> 
  <%= link_to "Back to notes", root_path, class:"btn btn-primary outline m-2" %>


  <%= button_to "Destroy this note", @note, method: :delete , class:"btn btn-danger m-2", form: { data: { turbo_confirm: "Are you sure?" } } %>
</div>



<% if @note.note_type  == "luoghi" %>


   <h1>Sublocations</h1>

<div id="sublocations">
  <% @note.sublocations.each do |sublocation| %>
    <%= render sublocation %>
    <p>
      <%= link_to "Show this sublocation", sublocation %>
    </p>
  <% end %>
</div>

<%= link_to "New sublocation", new_sublocation_path(luogo_n_id: @note.id) %>

<% end %>


<!--- https://www.b4web.biz/181/aggiungere-tramite-link-un-evento-su-google-calendar--></div>