config/routes.rb
Rails.application.routes.draw do
  resources :sublocations
  resources :prenotations
  resources :contacts
  resources :events
  resources :categories

  
  
  get 'dashboard/index'
  get 'dashboard/note'
  get 'dashboard/passate'
  get 'dashboard/eventi'
  get 'dashboard/soldi'
  get 'dashboard/energie'
  get 'dashboard/accessi'
  get 'dashboard/attenzione'
  get 'dashboard/luoghi'
  get 'dashboard/abilita'
  get 'dashboard/attivita'
  get 'dashboard/pastcalendar'
  resources :noteslots
  resources :slots
  get 'privata/pastslot'
  get 'privata/noslot'
  get 'privata/todoslot'
  
  resources :slots 
  resources :calendars do
    resources :categories
    member do
      get 'pastslot'
      get 'noslot'
      get 'todoslot'
      
      get "passate"
      get "future"
      get "settimana"
    end
  end 
  resources :notes
  resources :profiles do
    member do
      get "profslot"
      get "pubcalendar"
      get "pastcalendar"
      get "luoghi"
      get "passate"
      get "future"
      get "settimana"
    end 
  end

  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/pastcalendar'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "pages#home"

  root "pages#calendar"
  # authenticate :user do
   # root "dashboard#index", as: :authenticated_root
  # end

  

  
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :profile
  has_many :slots
  has_many :categories
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_calendar, only: %i[ show edit update destroy pastslot noslot todoslot future passate settimana]


  layout "dashboard"
  # GET /calendars or /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1 or /calendars/1.json
  def future
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
     # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
     # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end 
    @slots = @calendar.slots.where("data_start < ?", @data_start.beginning_of_day ) 
    if @slots
      @slots =  @slots.order(data_start: :desc)
    end 
    @profile = @calendar.profile
  end 

  def passate
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
    # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end 
    @slots = @calendar.slots.where("data_start > ?", @data_start.beginning_of_day )
    if @slots
      @slots =  @slots.order(data_start: :asc)
    end 
    @profile = @calendar.profile
  end 

  

  def settimana

    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i).beginning_of_week(start_day = :monday)
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now.beginning_of_week(start_day = :monday)
      @data_f = DateTime.now.strftime("%Y-%m-%d")
     
     # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end 
   

    @wkBegin = @data_start
    @wkEnd = (@data_start + 7.day).end_of_day
    @notes = @calendar.profile.notes.where(:start => @data_start.beginning_of_week..(@data_start.end_of_week + 23.hour))   
    @datas = @calendar.profile.notes.where(note_type: "data").where('data_start > ? AND data_end < ?',  @wkBegin, @wkEnd)  
    
    
    @new_data = params[:new_data]
  end

  def show
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end  
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
     # @notes = current_user.profile.notes.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
     # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end 
    @slots = @calendar.slots.where("data_start > ?", @data_start.beginning_of_day ) 
    if @slots
      @slots =  @slots.order(data_start: :desc)
    end 
    @profile = @calendar.profile
  end

  def pastslot
    if params[:date]
      date = params[:date]
      year = date[0, 4].to_i  
      month = date[5, 6].to_i 
      if month < 10 
        month = "0" + month.to_s
      end   
      day = date[8, 9].to_i  
      if day < 10 
        day =   "0" + day.to_s
      end   
      @data_start = DateTime.new(year.to_i,month.to_i,day.to_i) 
      
      @data_f = year.to_s + "-" + month.to_s  + "-" + day.to_s   
    else
      @data_start = DateTime.now
      @data_f = DateTime.now.strftime("%Y-%m-%d")
    # @slots = @calendar.slots.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    # @scheduledates = current_user.profiles.first.scheduledates.where(:start => @data_start.beginning_of_day..@data_start.end_of_day)   
    end 
    @slots = @calendar.slots.where("data_start < ?", @data_start.beginning_of_day )
    if @slots
      @slots =  @slots.order(data_start: :asc)
    end 
    @profile = @calendar.profile
  end

  def noslot
    @slots = @calendar.slots.where(data_start: nil )
  end
  def todoslot
    @slots = @calendar.slots.where(data_end: nil )
  end
  

  # GET /calendars/new
  def new
    @calendar = current_user.profile.calendars.build
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars or /calendars.json
  def create
    @calendar = current_user.profile.calendars.build(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to calendar_url(@calendar), notice: "Calendar was successfully created." }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1 or /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to calendar_url(@calendar), notice: "Calendar was successfully updated." }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1 or /calendars/1.json
  def destroy
    @calendar.destroy

    respond_to do |format|
      format.html { redirect_to calendars_url, notice: "Calendar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calendar_params
      params.require(:calendar).permit(:profile_id, :name, :description, :body, :image_square_url, :image_logo_url, :calendar_type, :luogo_note_id, :attivita_note_id, :gruppo_note_id, :public, :visibility,:data_start, :data_end, :responsabile_profile_id, :entrate, :uscite, :zoom_index, :hex_color)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_data_week.html.erb
<% if @new_data == "yes" %>
<div class="m-4">

  <%= link_to 'New data', "?new_data=#{day}", class: "btn btn-indigo " %>
 </div>
<% end %> 

<% if @new_data == day.to_s %>
  <%#= render 'new_data', day: day, date: date_d, data: @data, profile: current_user.profile  %> 
<% end %>




  <div class="space-y-1 m-auto bg-white"  >
  <% n_data = 0 %>
  
  <%  @datas.order("data_start ASC").each do |data| %>
  
      <%= render 'profiles/week/data', data: data, day: day, n_data: n_data %>

  <% if data.note_type == "data" %>
    <% n_data += 1 %>
  <% end %>

    
  <% end %>
    
    
</div>

app/views/calendars/_nav_cal.html.erb
<div style="overflow-x:auto;">
<ul class="list-none flex flex-wrap text-sm font-medium text-center text-gray-500 dark:text-gray-400">
    <% if user_signed_in?%> 
    
        <% if  current_user.profile %>
            <li class="mr-2">
        
                <% if (controller_name == "pages" && action_name == "home") || (controller_name == "notes" && action_name == "index")%> 
                    <%= link_to "ALL NOTE", notes_path(current_user.profile.id), class:" inline-block py-3 px-4 text-white bg-red-600 hover:bg-red-900 hover:text-gray-100 rounded-lg active" %>

                        <% else%>
                        <%= link_to "ALL NOTE", notes_path(current_user.profile.id), class:" inline-block text-red-600 py-3 px-4 rounded-lg hover:text-red-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white" %>          
                    <% end %>
            </li>
             <li class="mr-2">
                <% if (controller_name == "slots" && action_name == "index") || (controller_name == "privata" && action_name == "pastslot") || (controller_name == "privata" && action_name == "noslot") || (controller_name == "privata" && action_name == "todoslot") %> 
                    <%= link_to "ALL LINK", slots_path, class:" inline-block py-3 px-4 text-white bg-blue-600 hover:bg-blue-900 hover:text-gray-100 rounded-lg active" %>

                        <% else%>
                        <%= link_to "ALL LINK", slots_path, class:" inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white" %>          
                    <% end %>
            </li>

            <li class="mr-2">
            <% if controller_name == "calendars" && action_name == "index"%> 
                <%= link_to "CAL", calendars_path, class:" inline-block py-3 px-4 text-white bg-blue-600 hover:bg-blue-900 hover:text-gray-100 rounded-lg active" %>

                    <% else%>
                    <%= link_to "CAL", calendars_path, class:" inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white" %>          
                <% end %>
            </li>
           
            
    
        
        <% end %>
    
      <% end %>
    
  
    <% current_user.profile.calendars.where(data_end: nil).each do |cal|%>
        <li class="mr-2">
 
         
         <% if (controller_name == "calendars" &&  ["show", "pastslot", "todoslot", "noslot"].include?(action_name) && cal.id.to_s == params[:id].to_s) %> 
            <%= link_to cal.name, cal, class:" inline-block py-3 px-4 text-white bg-blue-600 hover:bg-blue-900 hover:text-gray-100 rounded-lg active" %>

                <% else%>
                <%= link_to cal.name, cal, class:" inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white" %>          
            <% end %>
          
        </li>
    <% end %>
    
 
</ul>
</div>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render "form", calendar: @calendar %>

<br>

<div>
  <%= link_to "Show this calendar", @calendar %> |
  <%= link_to "Back to calendars", calendars_path %>
</div>

app/views/calendars/index.html.erb
<div class="mx-auto">
<h2 class="m-4 pt-4">Calendari</h2>

<%= link_to "profilo",  profiles_path %>

<%= link_to "location",  root_path %>

<%= link_to "Eventi",  events_path %>


<div class="container my-12 mx-auto px-4 md:px-12">
<%= link_to "New calendar", new_calendar_path, class:"btn btn-danger m-4" %>

    <div class="flex flex-wrap -mx-1 lg:-mx-4">
    <!-- Column -->
       <div id="calendars" class="grid grid-cols-1  ">
       <div class="relative overflow-x-auto shadow-md sm:rounded-lg ">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                  <tr>
                      <th scope="col" class="px-6 py-3">
                          Profile
                      </th>
                      <th scope="col" class="px-6 py-3">
                          Nome
                      </th>
                      <th scope="col" class="px-6 py-3">
                          luogo
                      </th>
                      <th scope="col" class="px-6 py-3">
                          attività
                      </th>
                       <th scope="col" class="px-6 py-3">
                          Gruppo
                      </th>
                         <th>
                        pubblico
                      </th>
                      <th>
                        visibilità
                      </th>

                  </tr>
              </thead>
              <tbody>
                <% @calendars.each do |calendar| %>
               

 

  
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                           <img src="<%= calendar.image_logo_url %>" width="60px;">  <%= calendar.profile.username %>
                        </th>
                        <td class="px-6 py-4">
                                 <%= link_to calendar.name, calendar,  class:"font-medium text-text-fuchsia-500 dark:text-fuchsia-400-600 dark:text-text-fuchsia-500 dark:text-fuchsia-400-500 hover:underline" %>
                        </td>
                        <td class="px-6 py-4">
                            <%= calendar.calendar_type %>
                        </td>
                        <td class="px-6 py-4">
                               <%= calendar.luogo_note_id %>
                        </td>

                        <td class="px-6 py-4">
                                 <%= calendar.attivita_note_id %>
                        </td>
                             <td class="px-6 py-4">
                                <%= calendar.gruppo_note_id %>
                        </td>
                        <td class="px-6 py-4 text-right">
                          <%= calendar.visibility %>
                          
                        </td>
                    </tr>
                    
                  <% end %>
              </tbody>
          </table>
      </div>

      </div>
        
        <!-- END Column -->  
         

    </div>
</div>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render "form", calendar: @calendar %>

<br>

<div>
  <%= link_to "Back to calendars", calendars_path %>
</div>

app/views/calendars/noslot.html.erb
<h1>Slot </h1>

<%= render @calendar %>
<%= render 'slots/agenda_cal_slot' %>

app/views/calendars/passate.html.erb
<%= render "slots/agenda_cal_slot" %>

app/views/calendars/settimana.html.erb
<% if action_name != "passate" && action_name != "future" && action_name != "settimana" %>
         
  <%= render 'calendars/nav_cal' %> 
             
<% else %>  
 CALENDARIO: <%= @calendar.name %>  
<% end %>         
  <div class="mb-4 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
      <ul class="list-none flex flex-wrap -mb-px">
        
    <!--- menù dashboard-->
             
              
               <% if controller_name == "calendars" && action_name == "passate" %>
                <li class="mr-2">
                  <%= link_to 'Passate', passate_calendar_path(@calendar.id), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Passate', passate_calendar_path(@calendar.id), class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
                
              <% end %>
             <% if  controller_name == "calendars" && action_name == "future"%>
                <li class="mr-2">
                  <%= link_to 'Future', future_calendar_path(@calendar.id), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Future', future_calendar_path(@calendar.id),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>
               <% if  controller_name == "calendars" && action_name == "settimana"%>
                <li class="mr-2">
                  <%= link_to 'Settimana', settimana_calendar_path(@calendar.id), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                  
                  
                </li>
              <% else %>
                <li class="mr-2">
                  <%= link_to 'Settimana', settimana_calendar_path(@calendar.id),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                </li>
              
              <% end %>
        
          
            
            <% if user_signed_in? %>
               <% if current_user.profile %>
              
          
            
                <% if [@calendar.profile_id,@calendar.responsabile_profile_id].include?(current_user.profile.id) %>
                <% if controller_name == "calendars" && action_name == "pastslot" %>
                    <li class="mr-2">
                      <%= link_to 'Private Passate', pastslot_calendar_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                      
                    </li>
                  <% else %>
                    <li class="mr-2">
                      <%= link_to 'Private Passate', pastslot_calendar_path, class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                    </li>
                    
                  <% end %>
                <% if  controller_name == "calendars" && action_name == "show"%>
                    <li class="mr-2">
                      <%= link_to 'Private Future', calendar_path(@calendar.id), class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                      
                      
                    </li>
                  <% else %>
                    <li class="mr-2">
                      <%= link_to 'Private Future', calendar_path(@calendar.id),  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                    </li>
                  
                  <% end %>

                    <% if  controller_name == "calendars" && action_name == "noslot"%>
                    <li class="mr-2">
                      <%= link_to 'Non calendarizzate', noslot_calendar_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                      
                      
                    </li>
                  <% else %>
                    <li class="mr-2">
                      <%= link_to 'Non calendarizzate', noslot_calendar_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                    </li>
                  
                  <% end %>

                  <% if  controller_name == "calendars" && action_name == "todoslot"%>
                    <li class="mr-2">
                      <%= link_to 'Da finire', todoslot_calendar_path, class:"inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" %>
                      
                      
                    </li>
                  <% else %>
                    <li class="mr-2">
                      <%= link_to 'Da finire', todoslot_calendar_path,  class:"inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>   
                    </li>
                  
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
            <!-- end dashboard  -->         
         
          
            <!-- end pubblico  -->   
      

          
       
         
          
         
        
      </ul>
  </div>
<style>

.relativ {
  position:  relative;

  height: 3600px;
  
}



</style>
  <div class="flex flex-wrap mx-auto py-6 lg:px-0 mx-2">
    <div class="w-full  pr-0 mb-6">
      <div class=" m-4">
        <div class="p-4 m-4">

          <h2 class="max-w-md mb-4 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none xl:max-w-lg">
            <%= @wkBegin.strftime("%Y") %> Settimana n° <%= params[:n_week] %>
          </h2>
                          
          <%#= link_to '+ data', "?new_data=yes", class:"btn btn-indigo" %>
          <% if @new_data == "yes" %>
            <%= link_to 'Annulla', "../#{params[:year]}/#{params[:n_week]}", class: "btn btn-outline" %>
          <% end %> 
        </div>                   
            
          
              
      </div>
  
    </div>
  </div>
</div>

<div style="overflow-x:auto;">
    <div class="grid grid-rows-7 grid-flow-col gap-4" style="min-width:1100px;">
        
        <!-- inizio lun  ---> 
        <div class=" relativ">
      
            <%= link_to future_profile_path(@calendar.profile, date: @data_start.strftime("%Y-%m-%d")) do %>

            <h6 class="text-center mb-2 font-semibold leading-5">Lun <%= @wkBegin.strftime("%d/%m") %></h6>
            <% end %>
            <!-- inizio data --->
            <%= render 'data_week', day: 0, date_d: @wkBegin %>
            
            <!--fine  data  --->
        </div>
        <!-- fine lun  --->
        <!-- inizio mar  --->
        <div class=" relativ">
        
          <%= link_to future_profile_path(@calendar.profile, date: (@data_start + 1.day).strftime("%Y-%m-%d")) do %>
            <h6 class="text-center mb-2 font-semibold leading-5">Mar <%= (@wkBegin + 1.day).strftime("%d/%m") %>
            </h6>
            <% end %>
            
            
            <!-- inizio data --->
            <%= render 'data_week', day: 1, date_d: (@wkBegin + 1.day) %>
            
            <!--fine  data  --->
        </div>
        <!-- fine mar  --->
          <!-- inizio mer  --->
          <div class=" relativ">
        
              <%= link_to future_profile_path(@calendar.profile, date: (@data_start + 2.day).strftime("%Y-%m-%d")) do %>
                  <h6 class="text-center mb-2 font-semibold leading-5">
            Mer <%= (@wkBegin + 2.day).strftime("%d/%m") %></h6>
            <% end %>
      
            
            <!-- inizio data --->
            <%= render 'data_week', day: 2, date_d: (@wkBegin + 2.day) %>
            
            <!--fine  data  --->
        </div>
        <!-- fine mer  --->
          <!-- inizio gio  --->
          <div class=" relativ">
        
                                      <%= link_to future_profile_path(@calendar.profile, date: (@data_start + 3.day).strftime("%Y-%m-%d")) do %>

                <h6 class="text-center mb-2 font-semibold leading-5">Gio <%= (@wkBegin + 3.day).strftime("%d/%m") %></h6>
            
            <% end %>
            
            <!-- inizio data --->
            <%= render 'data_week', day: 3, date_d: (@wkBegin + 3.day) %>
            
            <!--fine  data  --->
        </div>
        <!-- fine gio  --->
          <!-- inizio ven  --->
          <div class=" relativ">
        
                                    <%= link_to future_profile_path(@calendar.profile, date: (@data_start + 4.day).strftime("%Y-%m-%d")) do %>

              <h6 class="text-center mb-2 font-semibold leading-5">Ven <%= (@wkBegin + 4.day).strftime("%d/%m") %></h6>
            
            <% end %>
            
            <!-- inizio data --->
            <%= render 'data_week', day: 4, date_d: (@wkBegin + 4.day) %>
            
            <!--fine  data  --->
        </div>
        <!-- fine ven  --->
          <!-- inizio sab  --->
        <div class=" relativ">
        
                                      <%= link_to future_profile_path(@calendar.profile, date: (@data_start + 5.day).strftime("%Y-%m-%d")) do %>
              <h6 class="text-center mb-2 font-semibold leading-5">Sab <%= (@wkBegin + 5.day).strftime("%d/%m") %></h6>
          
            
            <% end %>
            
            <!-- inizio data --->
            <%= render 'data_week', day: 5, date_d: (@wkBegin + 5.day) %>
            
            <!--fine  data  --->
        </div>
        <!-- fine sab  --->
          <!-- inizio dom  --->
          <div class=" relativ">
        
              <%= link_to future_profile_path(@calendar.profile, date: (@data_start + 6.day).strftime("%Y-%m-%d")) do %>

            <h6 class="text-center mb-2 font-semibold leading-5">Dom <%=   @wkEnd.strftime("%d/%m") %></h6>
            
            <% end %>
            
            <!-- inizio data --->
            <%= render 'data_week', day: 6, date_d: @wkEnd %>
            
            <!--fine  data  --->
        </div>
        <!-- fine dom  --->

    </div>
</div>

app/views/calendars/show.html.erb
<%= link_to "profilo",  profiles_path %>

<%= link_to "location",  root_path %>

<%= link_to "Eventi",  events_path %>
<%= link_to "Categrie",  categories_path %>


<%= render @calendar %>


<h2>Categorie Evento da aggiungere</h2>
<div>
<div class="flex"> 
<div class="m-2 "> 
  <%= link_to "Edit this calendar", edit_calendar_path(@calendar), class:"btn btn-primary" %> 
 </div>
 <div class="m-2"> 
  <%= link_to "Back to calendars", calendars_path, class:"btn btn-primary" %>
 </div>
 <div class="m-2"> 
  <%= button_to "Destroy this calendar", @calendar, method: :delete, class:"btn btn-danger", form: { data: { turbo_confirm: "Are you sure?" } } %>
</div>
</div>
<% if current_user.profile.id == @calendar.profile.id %>
    <div class="my-4">
    <%= link_to "+ data calendario", new_slot_path(calendar_id: @calendar.id), class:"btn btn-primary" %>
  </div>
<% end %>

<div>

<h2>
<%= link_to 'Categorie', calendar_categories_path(@calendar), class:"btn btn-primary m-4" %>
</h2>
<%= render 'slots/agenda_cal_slot' %>


</div>

<div class="h-40">
</div>